name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' 

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  
  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x' 

    - name: Install dependencies (for test)
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

