name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' 

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  
  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x' 

    - name: Install dependencies (for test)
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
  set-up-dotnet:
   runs-on: ubuntu-latest  # Specifies the environment to run the job
   steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'  # Install .NET 6.x

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'  # Install .NET 7.x
